# Generated by Django 5.1 on 2024-09-16 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0002_alter_pedido_descricao'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pedido',
            new_name='Pedidos',
        ),
    ]
